In [1]:
%pylab

Using matplotlib backend: Qt4Agg
Populating the interactive namespace from numpy and matplotlib


In [15]:
%pylab?

In [1]:
import numpy as np

In [ ]:
print dir(np),

In [ ]:
np.__version__

In [3]:
import pandas as po

In [4]:
po.__version__

u'0.19.2'

In [6]:
import os

In [7]:
print os.getcwd() # to get the current directory

C:\Users\admin\pandas


In [8]:
os.listdir(os.getcwd())

['.ipynb_checkpoints',
 '2- Numpy Tutorial.pdf',
 '3 - Pandas.pdf',
 'Basic Python Exercise Solutions.ipynb',
 'DataSets',
 'NumPy_Prac.ipynb',
 'Pandas-1.ipynb',
 'Pandas-2.ipynb',
 'Pandas-Series.ipynb',
 'Pandas_prac.ipynb',
 'titanic3.csv',
 'towed.db',
 'Untitled.ipynb']

In [12]:
# os.chdir(<path>) # set a directory as cwd

---

## NumPy


NumPy is built for efficient scientific data analysis and Pandas is for general data analysis.

All indexers in Python start at 0 or (0, 0)

###Creating an ndarray

**tuple** and **list** are equivalent of a 1-dim array. Numpy provides ndarray to have easy and efficient control over the 1 dim arrays so created in Python.

In [10]:
# Array or ndarray (object data structure) is a 1d or 2d or nd linear
# data structure

# array() - > a python list as input adn converts it into an ndarray

In [29]:
# Creating an nd array
list1 = [12,45,34,23,33,54,56,21,11,15]
arr1 = np.array(list1)
# np.array((12,45,34,23,33,54,56,21,11,15))

# obvious that a list/tuple is going as input and getting converted to a numpy array

In [30]:
arr1

array([12, 45, 34, 23, 33, 54, 56, 21, 11, 15])

In [31]:
type(arr1)

numpy.ndarray

In [ ]:
# Associated functions and attibutes :
print dir(arr1),

In [ ]:
a = np.array([1, 2, 3]) # Create a rank 1 array
print type(a) # Prints "<type 'numpy.ndarray'>"
print a.shape # Prints "(3,)"
print a[0], a[1], a[2] # Prints "1 2 3"
a[0] = 5 # Change an element of the array
print a # Prints "[5, 2, 3]"
b = np.array([[1,2,3],[4,5,6]]) # Create a rank 2 array
print b.shape # Prints "(2, 3)"
print b[0, 0], b[0, 1], b[1, 0] # Prints "1 2 4"

In [18]:
arr1.shape()

TypeError: 'tuple' object is not callable

In [20]:
arr1

array([12, 45, 34, 23, 33, 54, 56, 21, 11, 15])

In [19]:
# get length and dimensions
arr1.shape # it's an attribute, not a function.
# arr1.shape() is a syntax error

(10L,)

In [21]:
# Getting elements by index - []
arr1[0]

12

In [22]:
arr1[1:3] # subset of array

array([45, 34])

In [20]:
arr1[-1] # from the RHS

15

In [32]:
# edit an element
arr1[4] = 123
arr1

# Add elelments to an existing array
np.append(arr = arr1,values = 144)
np.insert()

array([ 12,  45,  34,  23, 123,  54,  56,  21,  11,  15, 144])

In [61]:
# the range function in python
end_point = 10
range(end_point) # 0 to n-1
# output is a list

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [62]:
# similar range function from numpy
arange(end_point) # same 0 to n-1
# but creates an array instead


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [65]:
start_point = 1
arr1d = arange(start_point,end_point)
# start_point to end_point-1
arr1d

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
# Creating a 2d array

arr2d = np.array([1,2,3]); print arr2d # that will be the normal 1d array

[1 2 3]


In [4]:
type(arr2d)

numpy.ndarray

In [7]:
arr2d.ndim

1

In [8]:
# arr2d = np.array(   [  [],[],[]  ]  )
arr2d = np.array([[11,23,12],[34,79,41],[56,54,78],[5,4,7]])
arr2d

array([[11, 23, 12],
       [34, 79, 41],
       [56, 54, 78],
       [ 5,  4,  7]])

In [9]:
arr2d.shape

(4L, 3L)

In [11]:
arr2d_1 = np.array([[11,23,12],[34,79,41],[12],[56,54,78],[5,4,7]])
print arr2d_1

[[11, 23, 12] [34, 79, 41] [12] [56, 54, 78] [5, 4, 7]]


In [12]:
arr2d_1.ndim

1

In [19]:
arr2 = np.array([12,77,2,6,3,11,98,10,2,6,10,23])
arr2.shape

(12L,)

In [25]:
arr3 = arr2.reshape(4,3)

In [26]:
arr3

array([[12, 77,  2],
       [ 6,  3, 11],
       [98, 10,  2],
       [ 6, 10, 23]])

In [27]:
arr3.reshape(12)

array([12, 77,  2,  6,  3, 11, 98, 10,  2,  6, 10, 23])

In [14]:
list2 = [12,45,66,[99,22,44],["A","N","M"]]
list2

[12, 45, 66, [99, 22, 44], ['A', 'N', 'M']]

In [36]:
arr2d.shape # A 3 X 3 matrix

(4L, 3L)

In [28]:
# using arange() for getting a 2d array

# use reshape function to convert a 1d array to 2d array. 
# It sets the no of rows and no of columns

arr2d1 = np.arange(30).reshape(5,6)


In [29]:
# The size of the 2-d array must be in multiples of the total len
# of the input array

arr2d1 = np.arange(30).reshape(6,5)
arr2d1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [ ]:
a = np.zeros((2,3)) # Create an array of all zeros
print a 
print a.dtype
b = np.ones((4,2)) # Create an array of all ones
print b
c = np.full((2,2), 7) # Create a constant array
print c
d = np.random.random((2,2)) # Create an array filled with random values
#print d

In [31]:
x = 0.
type(x)
arr2d

array([[11, 23, 12],
       [34, 79, 41],
       [56, 54, 78],
       [ 5,  4,  7]])

In [30]:
# Slicing a 2d array
# arr2d[rows from:to:step, columns from:to:step]
# Row 2
arr2d[1,]

array([34, 79, 41])

In [34]:
# all rows from row 2
arr2d[1:,]
arr2d

array([[11, 23, 12],
       [34, 79, 41],
       [56, 54, 78],
       [ 5,  4,  7]])

In [36]:
# col no 2
print arr2d[:,1]

[23 79 54  4]


In [ ]:
# Error because in selecting row 1, we select all columns, so that must be specified
arr2d[:,1]

In [ ]:
# Creating boolean indexes - applying conditions
arr2d > 20

In [ ]:
arr2d[arr2d > 20]

In [ ]:
# getting datatype of an array

# type() talks about the overall data structure
type(arr2d)

In [ ]:
# dtype attribute results in the datatype
arr2d.dtype

In [ ]:
arr1

In [ ]:
arr1 > 20 # Boolean array

In [ ]:
arr1[arr1 < 20]

In [ ]:
arr2 = np.array([1,2,10,11,12,6,7,3,5,7])

print (arr1 * (2))
arr1

In [ ]:
# Array arithmaic

In [37]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]])

In [38]:
print x

[[ 1.  2.]
 [ 3.  4.]]


In [39]:
print y

[[5 6]
 [7 8]]


In [40]:
x + y

array([[  6.,   8.],
       [ 10.,  12.]])

In [ ]:
x1 = np.array([[1,2],[3,4]])
print np.sum(x) # Compute sum of all elements; prints "10"
print np.sum(x, axis=0) # Compute sum of each column; prints "[4 6]"
print np.sum(x, axis=1) # Compute sum of each row; prints "[3 7]"

In [ ]:
arr3 = np.array([10,20,30])
arr1

In [ ]:
arr1 + arr3

In [ ]:
arr1

In [ ]:
np.any(arr1 < 20)

In [ ]:
np.all(arr1 < 20)

In [ ]:
np.all(arr1 > 0)

In [ ]:
# Documents or Users
import os

In [88]:
os.getcwd()

'C:\\Users\\admin\\pandas'

In [89]:
os.chdir("C:\\Users\\admin\\pandas\\DataSets")

In [ ]:
print os.listdir(os.getcwd()),