In [1]:
l1 = [12,67,99,103,24,56,54,79,20,10]

In [2]:
type(l1)

list

In [4]:
print dir(l1),

['__add__', '__class__', '__contains__', '__delattr__', '__delitem__', '__delslice__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getslice__', '__gt__', '__hash__', '__iadd__', '__imul__', '__init__', '__iter__', '__le__', '__len__', '__lt__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__reversed__', '__rmul__', '__setattr__', '__setitem__', '__setslice__', '__sizeof__', '__str__', '__subclasshook__', 'append', 'count', 'extend', 'index', 'insert', 'pop', 'remove', 'reverse', 'sort']


In [5]:
l1[8]

20

In [6]:
l1[:6]

[12, 67, 99, 103, 24, 56]

In [7]:
l1[4:]

[24, 56, 54, 79, 20, 10]

In [8]:
l1[1::2]

[67, 103, 56, 79, 10]

In [9]:
# Numerical Python
# Single elemnt base operations

# Set based operations
# Matrix based operations

# Calculus
# Trig

In [ ]:
# 1. Get the 1-d and 2-d DS from numpy
# 2. maths functions - average, sd, variance, skewness, kurtosis, min, max
# 3. conditional operator - equivalent to python ternary if
# 4. generating randon numbers
# 5. sampling 
# 6. sqrt, cube, power, trig

In [ ]:
# What to learn
# ndarrays - n dim arrays

In [10]:
import numpy as np

In [11]:
# ndarrays
# Creating 1-d arrays in numpy

# np.array() will create an array of n dimensions
# It converts a list or a group of lists to an ndarray
l1

[12, 67, 99, 103, 24, 56, 54, 79, 20, 10]

In [17]:
arr1 = np.array([12, 67, 99, 103, 24, 56, 54, 79, 20, 10])

In [18]:
arr1

array([ 12,  67,  99, 103,  24,  56,  54,  79,  20,  10])

In [19]:
type(arr1)

numpy.ndarray

In [20]:
print dir(arr1),

['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_interface__', '__array_prepare__', '__array_priority__', '__array_struct__', '__array_wrap__', '__class__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__delslice__', '__div__', '__divmod__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getslice__', '__gt__', '__hash__', '__hex__', '__iadd__', '__iand__', '__idiv__', '__ifloordiv__', '__ilshift__', '__imod__', '__imul__', '__index__', '__init__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__long__', '__lshift__', '__lt__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__nonzero__', '__oct__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdiv__', '__rdivmod__', '__reduce__', '__reduce_ex__', '__repr__', '__rfloordiv__', '__rlshift__', '__rmod__

In [21]:
arr1.mean()
arr1.min()
arr1.max()
arr1.std()
arr1.var()
arr1.cumprod()
arr1.cumsum()

array([ 12,  79, 178, 281, 305, 361, 415, 494, 514, 524])

In [23]:
arr1.dtype

dtype('int32')

In [25]:
# dtype - datatype of the constituent objects
# arrays are designed to be strictly homogenous - all the elements must have one datatype

arr2 = np.array([1,2,3,4,"A","B",True,12.0])

In [29]:
arr2.dtype

dtype('S11')

In [30]:
arr3 = np.array([6,7,8,9.0,23.8])

In [31]:
arr3.dtype

dtype('float64')

dict                     ndarray
list
tuple

str                     s11 or Object
float                   float64
long                    int64 or int32
int

bool                    bool


In [32]:
arr1

array([ 12,  67,  99, 103,  24,  56,  54,  79,  20,  10])

In [34]:
arr2 = np.array([45,67,10,32,10,34,11,56,90,11])
arr2

array([45, 67, 10, 32, 10, 34, 11, 56, 90, 11])

In [35]:
arr1.shape

(10L,)

In [36]:
arr2.shape

(10L,)

In [37]:
l2 = [45, 67, 10, 32, 10, 34, 11, 56, 90, 11]

In [39]:
l3 = l1 + l2

In [41]:
print l3,

[12, 67, 99, 103, 24, 56, 54, 79, 20, 10, 45, 67, 10, 32, 10, 34, 11, 56, 90, 11]


In [42]:
arr1 + arr2

array([ 57, 134, 109, 135,  34,  90,  65, 135, 110,  21])

In [43]:
arr1

array([ 12,  67,  99, 103,  24,  56,  54,  79,  20,  10])

In [44]:
arr2

array([45, 67, 10, 32, 10, 34, 11, 56, 90, 11])

In [45]:
arr1 * 10

array([ 120,  670,  990, 1030,  240,  560,  540,  790,  200,  100])

In [46]:
arr1[7] # indexing always begins with 0

79

In [47]:
arr1[:9]

array([ 12,  67,  99, 103,  24,  56,  54,  79,  20])

In [48]:
l1

[12, 67, 99, 103, 24, 56, 54, 79, 20, 10]

In [49]:
opl = []
for i in l1:
    if i > 70:
        opl.append(i)
    

In [50]:
opl

[99, 103, 79]

In [55]:
opl2 = [x for x in l1 if x > 70]

In [56]:
opl2

[99, 103, 79]

In [57]:
# boolean array
l1 > 70

True

In [60]:
ba = (arr1 > 70)

In [61]:
arr1[(arr1 > 70)]

array([ 99, 103,  79])

In [64]:
# > 30 and < 60
arr1[(arr1 > 30) & (arr1 < 70)]

array([67, 56, 54])

In [67]:
x = -10
print "positive" if x > 0 else "negative"

negative


In [70]:
x = 0
"zero" if x == 0 else "positive" if x > 0 else "negative"

'zero'

In [72]:
if x == 0:
    print "zero"
elif x > 0:
    print "positive"
else:
    print "negative"

zero


In [74]:
l1 > 50
opl = []
for i in l1:
    if i > 50:
        opl.append(i)

In [75]:
opl

[67, 99, 103, 56, 54, 79]

In [ ]:
for i in l1: if i > 50: opl.append(i)

In [77]:
[i for i in l1 if i > 50]

[67, 99, 103, 56, 54, 79]

In [87]:
x = raw_input().split(",")

12,12,33,45


In [88]:
x

['12', '12', '33', '45']